# Generated by Django 4.2.6 on 2023-11-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmiot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='isWorking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurementType',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='primaryKey',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.IntegerField(max_length=50),
        ),
    ]
