# Generated by Django 4.2.7 on 2023-12-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmiot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="dimension",
            field=models.CharField(default="°C", max_length=10),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="measurementName",
            field=models.CharField(default="Name", max_length=250),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="measurementType",
            field=models.CharField(default="Type", max_length=250),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="value",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
