# Generated by Django 4.2.7 on 2023-12-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmiot', '0002_measurement_dimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=None)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmiot.measurement')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
