# Generated by Django 4.2.6 on 2023-12-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmiot', '0003_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
