# Generated by Django 4.2.6 on 2023-11-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmiot', '0003_measurement_measurementname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='primaryKey',
            field=models.IntegerField(default=0),
        ),
    ]
