# Generated by Django 3.2.8 on 2023-12-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmiot', '0003_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='last_notified',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='max_comfort',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='measurement',
            name='min_comfort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='need_notification',
            field=models.BooleanField(default=False),
        ),
    ]
