# Generated by Django 4.2.6 on 2023-11-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmiot', '0004_alter_measurement_primarykey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='primaryKey',
        ),
    ]
