# Generated by Django 4.2.6 on 2023-12-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmiot', '0004_auto_20231208_1203'),
        ('pmiot', '0004_measurement_image'),
    ]

    operations = [
    ]
