# Generated by Django 4.2.7 on 2023-11-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmiot", "0005_remove_measurement_primarykey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={"ordering": ["measurementName"]},
        ),
        migrations.AddField(
            model_name="measurement",
            name="max_value",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="measurement",
            name="min_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
